### ISSUE TITLE
Update to latest ByteString (package seems to be renamed)

### ISSUE THREAD

**Issue by maerten** [SamProtas/JuicyPixels-blurhash#15]
When trying to compile on GHC9.4 and latest stack nightly, i'm seeing this build error:

```
JuicyPixels-blurhash             > [2 of 7] Compiling Codec.Picture.Blurhash.Internal.Common
JuicyPixels-blurhash             > ............../JuicyPixels-blurhash-0.1.0.3/src/Codec/Picture/Blurhash/Internal/Base83.hs:20:1: error:
JuicyPixels-blurhash             >     Could not find module ‘Data.ByteString.Lazy.Builder’
JuicyPixels-blurhash             >     Perhaps you meant
JuicyPixels-blurhash             >       Data.ByteString.Builder (from bytestring-0.11.4.0)
JuicyPixels-blurhash             >       Data.ByteString.Lazy.Lens (needs flag -package-id lens-5.2.2)
JuicyPixels-blurhash             >       Data.ByteString.Lazy.UTF8 (needs flag -package-id utf8-string-1.0.2)
JuicyPixels-blurhash             >     Use -v (or `:set -v` in ghci) to see a list of the files searched for.
JuicyPixels-blurhash             >    |
JuicyPixels-blurhash             > 20 | import qualified Data.ByteString.Lazy.Builder as BS
JuicyPixels-blurhash             >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
JuicyPixels-blurhash             > [3 of 7] Compiling Codec.Picture.Blurhash.Internal.DList
```

Using the updated fork https://github.com/singpolyma/JuicyPixels-blurhash fixed this on my machine.
